//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using ws.winx.devices;
using System.Collections.Generic;

namespace ws.winx.platform
{
		public interface IHIDInterface:IDisposable
		{
            
			IDriver defaultDriver{get;set;}
			IDeviceCollection Devices{get;}
            Dictionary<IDevice, HIDDevice> Generics{get;}
            void Read(IDevice device,HIDDevice.ReadCallback callback);
            void Read(IDevice device, HIDDevice.ReadCallback callback,int timeout);
            void Write(object data, IDevice device, HIDDevice.WriteCallback callback, int timeout);
            void Write(object data, IDevice device,HIDDevice.WriteCallback callback);
            void Write(object data, IDevice device);
			void Update();
		    

		}
}

