//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Runtime.Serialization;

namespace ws.winx.input
{
		[DataContract]
		public class InputState
		{
				  
				[DataMember(Name = "InputCombinations")]
				public InputCombination[] combinations;

				public int hash {
						get {
								return _hash;
						}
				}

				
				public string name {
						get {
								return _name;
						}
						//set{ _name=value; }

				}

				[DataMember(Name = "Name")]
				protected string _name;

				[DataMember(Name = "Hash")]
				protected int _hash;

				protected int _count=0;

				public InputState (string name, int hash)
				{
						this._name = name;
						this._hash = hash;
						this.combinations = new InputCombination[2];
				}

				

				public void Add (InputCombination combination, int inx=-1)
				{
						
								
						
						if (inx > 0)
								this.combinations [inx] = combination;
						else
							this.combinations [_count++] = combination;
				}
		}
}

